#ifndef ASLAM_CV_COMMON_CHANNEL_DEFINITIONS_H_
#define ASLAM_CV_COMMON_CHANNEL_DEFINITIONS_H_

#include <Eigen/Dense>
#include <aslam/common/channel-declaration.h>

DECLARE_CHANNEL(VISUAL_KEYPOINT_MEASUREMENTS, Eigen::Matrix2Xd);
DECLARE_CHANNEL(VISUAL_KEYPOINT_MEASUREMENT_UNCERTAINTIES, Eigen::VectorXd);
DECLARE_CHANNEL(VISUAL_KEYPOINT_ORIENTATIONS, Eigen::VectorXd);
DECLARE_CHANNEL(VISUAL_KEYPOINT_SCALES, Eigen::VectorXd);
DECLARE_CHANNEL(VISUAL_KEYPOINT_SCORES, Eigen::VectorXd);
DECLARE_CHANNEL(DESCRIPTORS, Eigen::Matrix<unsigned char, Eigen::Dynamic, Eigen::Dynamic>);
DECLARE_CHANNEL(CV_MAT, cv::Mat);
DECLARE_CHANNEL(RAW_IMAGE, cv::Mat);


#endif  // ASLAM_CV_COMMON_CHANNEL_DEFINITIONS_H_
